# Generated by Django 4.1.12 on 2023-11-29 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerExistingPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('time_in', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('volume_in', models.FloatField()),
                ('symbol', models.CharField(max_length=255)),
                ('price_in', models.FloatField()),
                ('sl', models.FloatField(default=0.0, null=True)),
                ('tp', models.FloatField(default=0.0, null=True)),
                ('volume_out', models.FloatField(null=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('price_out', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('swap', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('trader_name', models.CharField(max_length=255)),
                ('is_closed', models.BooleanField(default=False, null=True)),
                ('server', models.CharField(max_length=255)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'consumer_existing_positions',
            },
        ),
        migrations.CreateModel(
            name='ConsumerTargetPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_in', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('volume_in', models.FloatField()),
                ('symbol', models.CharField(max_length=255)),
                ('price_in', models.FloatField()),
                ('sl', models.FloatField(default=0.0, null=True)),
                ('tp', models.FloatField(default=0.0, null=True)),
                ('volume_out', models.FloatField(null=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('price_out', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('swap', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('trader_name', models.CharField(max_length=255)),
                ('is_closed', models.BooleanField(default=False, null=True)),
                ('server', models.CharField(max_length=255)),
                ('is_created', models.BooleanField(default=False, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'consumer_target_positions',
            },
        ),
        migrations.CreateModel(
            name='ProviderExistingPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('reason', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('comment', models.CharField(max_length=255)),
                ('trader_uid', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('ticket', models.BigIntegerField()),
                ('sl', models.FloatField(null=True)),
                ('tp', models.FloatField(null=True)),
                ('comission', models.FloatField(null=True)),
                ('swap', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('time', models.BigIntegerField()),
                ('time_msc', models.BigIntegerField()),
                ('time_update', models.BigIntegerField()),
                ('time_update_msc', models.BigIntegerField()),
            ],
            options={
                'db_table': 'provider_existing_positions',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('server', models.CharField(max_length=45)),
                ('is_consumer', models.BooleanField(default=False)),
                ('terminal_id', models.CharField(blank=True, max_length=45, null=True)),
                ('trader_type', models.CharField(choices=[('AGGRESSIVE', 'AGGRESSIVE'), ('BALANCED', 'BALANCED'), ('CONSERVATIVE', 'CONSERVATIVE')], default='BALANCED', max_length=255)),
                ('trader_uid', models.CharField(blank=True, max_length=45, null=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('coefficient', models.FloatField(default=1.0)),
                ('balance', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'traders',
            },
        ),
    ]
