# Generated by Django 4.1.12 on 2023-11-29 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_in', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('volume_in', models.FloatField()),
                ('symbol', models.CharField(max_length=255)),
                ('price_in', models.FloatField()),
                ('sl', models.FloatField(default=0.0, null=True)),
                ('tp', models.FloatField(default=0.0, null=True)),
                ('volume_out', models.FloatField(null=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('price_out', models.FloatField(null=True)),
                ('commission', models.FloatField(default=0.0, null=True)),
                ('swap', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('trader_name', models.CharField(max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('server', models.CharField(max_length=255)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'original_positions',
            },
        ),
        migrations.CreateModel(
            name='ConsumerState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('starting_balance', models.FloatField()),
                ('balance_update', models.DateTimeField(auto_now_add=True)),
                ('starting_equity', models.FloatField()),
                ('can_trade', models.BooleanField(default=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_state', to='home.trader')),
            ],
            options={
                'db_table': 'consumer_state',
            },
        ),
    ]
